#/usr/bin/python3

'''
This is a python script which takes two arguments as input.
The first argument is a pcap file generated by dpdk_snoop_app.
The second argument is the standard output of the dpdk_snoop_app.
The script converts each of the input files to their respective json files.
The json files consist of information for each packets.
Next,it compares both the output of json file,and produces result accordingly.
'''

import sys
import os
import json
import argparse
import pathlib

#Setup arguments
parser = argparse.ArgumentParser()
parser.add_argument('pcap_file',help="This is a pcap file generated by dpdk_snoop_app which contains details of transferred packets")
parser.add_argument('standard_output_file',help="This is the standard output generated by dpdk_snoop_app which contains details of transferred packets")

args = parser.parse_args()

FILE_EXT=pathlib.Path(args.pcap_file).suffix
if FILE_EXT != '.pcap':
    exit("The first argument should be a pcap file")

# Initialize Variables
DIR=os.path.dirname(os.path.abspath(sys.argv[0]))
PACP_PARSER='{}/pcap_file_analyzer.py'.format(DIR)
PANDA_PARSER='{}/panda_parser.py'.format(DIR)
TMPDIR='/tmp'

# Generate the output and save to json file
try:
    os.system('python3 {} {} > {}/pcap_parser.json'.format(PACP_PARSER,args.pcap_file,TMPDIR))
except:
    exit("Error while generating the json output for pcap file of dpdk_snoop_app")

try:
    os.system('python3 {} {} > {}/panda_parser.json'.format(PANDA_PARSER,args.standard_output_file,TMPDIR))
except:
    exit("Error while generating the json output for stdout text file of dpdk_snoop_app")

# Load the json file path
PATH1='{}/pcap_parser.json'.format(TMPDIR)
PATH2='{}/panda_parser.json'.format(TMPDIR)

# Read the json files
try:
    j1=open(PATH1,)
    j2=open(PATH2,)
except:
    exit("Error while opening the json files")
try:
    data1=json.load(j1)
    data2=json.load(j2)
except:
    exit("Error while loading the data of json files")

# Compare the json files
if (data1==data2):
    print("Successful")
else:
    print("Unsuccessful")
